# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 287)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tasteLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tasteLineEdit.setGeometry(QtCore.QRect(144, 98, 234, 22))
        self.tasteLineEdit.setObjectName("tasteLineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 11, 117, 22))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 156, 117, 22))
        self.label_7.setObjectName("label_7")
        self.typeLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.typeLineEdit.setGeometry(QtCore.QRect(144, 69, 234, 22))
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 69, 117, 22))
        self.label_4.setObjectName("label_4")
        self.priceLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceLineEdit.setGeometry(QtCore.QRect(144, 127, 234, 22))
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.roastingLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roastingLineEdit.setGeometry(QtCore.QRect(144, 40, 234, 22))
        self.roastingLineEdit.setObjectName("roastingLineEdit")
        self.weightLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.weightLineEdit.setGeometry(QtCore.QRect(144, 156, 234, 22))
        self.weightLineEdit.setObjectName("weightLineEdit")
        self.gradeLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.gradeLineEdit.setGeometry(QtCore.QRect(144, 11, 234, 22))
        self.gradeLineEdit.setObjectName("gradeLineEdit")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 98, 117, 22))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 127, 117, 22))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 117, 22))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 190, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "название сорта"))
        self.label_7.setText(_translate("MainWindow", "объем упаковки"))
        self.label_4.setText(_translate("MainWindow", "молотый/в зернах"))
        self.label_5.setText(_translate("MainWindow", "описание вкуса"))
        self.label_6.setText(_translate("MainWindow", "цена"))
        self.label_3.setText(_translate("MainWindow", "степень обжарки"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
